### ISSUE TITLE
Source kernel ido

### ISSUE THREAD

**Issue by cleverior** [ido-dev/android_device_xiaomi_ido#2]
do u use prebuilt kernel to build and run CM12.1 and CM13 ? If yes, then i think this line https://github.com/ido-dev/android_device_xiaomi_ido/blob/cm-13.0/BoardConfig.mk#L53 isn't needed. Or you have source kernel for ido ? could you share it, please ?

**Comment by Anik1199** [comment]
I am still waiting for kernel source

**Comment by cleverior** [comment]
do u active on hangouts ? i just sent you message
