### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by TingyiChen** [ido-dev/android_device_xiaomi_ido#4]
make: **\* No rule to make target '/home/chentingyi/RR/out/target/product/ido/obj/KERNEL_OBJ/usr', needed by '/home/chentingyi/RR/out/target/product/ido/obj/STATIC_LIBRARIES/libsdcard_intermediates/sdcard.o'

How to solve this?

**Comment by Anik1199** [comment]
Tree isn't ready yet!

**Comment by TingyiChen** [comment]
i didn't clone the kernel repository,is it necessary to clone it?
